# -*- coding: utf-8 -*-
"""AI_ exam01_introduction_of_Deeplearning2025.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sx4D4IYC2kP9Prnkk0bMFv9YsJ5AlbPA

#딥러닝 입문

##Linear regression

###기존의 프로그래밍 방식
"""

def celsius_to_fahrenheit(x):
    return x * 1.8 + 32

celsius_value  = int(input('섭씨온도를 입력하세요. : '))
print('화씨온도로', celsius_to_fahrenheit(celsius_value), '도 입니다.')

"""###딥러닝 방식"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer
import numpy as np
import matplotlib.pyplot as plt

data_C = np.array(range(0, 100))
data_F = celsius_to_fahrenheit(data_C)
print(data_C)
print(data_F)

model = Sequential()
model.add(InputLayer(input_shape=(1,)))
model.add(Dense(1))
model.compile(loss='mse', optimizer='rmsprop')
model.summary()

scaled_data_C = data_C / 100
scaled_data_F = data_F / 100
print(scaled_data_C)
print(scaled_data_F)

print(model.predict(np.array([0.01])))

model.save('before_learning.h5')

fit_hist = model.fit(scaled_data_C, scaled_data_F, epochs=1000)

plt.plot(fit_hist.history['loss'])
plt.show()

print(model.predict(np.array([0.01])))

model.save('after_learning.h5')

import h5py

filename = "before_learning.h5"

with h5py.File(filename, 'r') as f:
    # 파일 내용 확인 (예: 키 목록을 출력하거나, 특정 데이터에 접근)
    print(list(f['model_weights']['dense']['sequential']['dense']['kernel']))
    print(list(f['model_weights']['dense']['sequential']['dense']['bias']))

filename = "after_learning.h5"

with h5py.File(filename, 'r') as f:
    # 파일 내용 확인 (예: 키 목록을 출력하거나, 특정 데이터에 접근)
    print(list(f.keys()))
    print(list(f['model_weights']['dense']['sequential']['dense']['kernel']))
    print(list(f['model_weights']['dense']['sequential']['dense']['bias']))

celsius_value  = int(input('섭씨온도를 입력하세요. : '))
print('화씨온도로', (model.predict(np.array([celsius_value/100]))*100), '도 입니다.')

noise = np.random.normal(0, 0.05, 100)
print(noise)

noised_scaled_data_F = np.array([])
for data in scaled_data_F:
    noised_scaled_data_F = np.append(
        noised_scaled_data_F, np.random.normal(0, 0.05, 100) + data)
print(noised_scaled_data_F)
print(len(noised_scaled_data_F))

noised_scaled_data_C = []
for data in range(100):
    for i in range(100):
        noised_scaled_data_C.append(data)
noised_scaled_data_C = np.array(noised_scaled_data_C)
noised_scaled_data_C = noised_scaled_data_C / 100
print(noised_scaled_data_C)
print(len(noised_scaled_data_C))

fig = plt.figure(figsize=(20, 20))
ax = fig.add_subplot(111)
ax.scatter(noised_scaled_data_C, noised_scaled_data_F, alpha=0.2, s=200, marker='+')
plt.show()

model1 = Sequential()
model1.add(InputLayer(input_shape=(1,)))
model1.add(Dense(1))
model1.compile(loss='mse', optimizer='rmsprop')
model1.summary()

print(model1.predict(np.array([0.01])))

fit_hist = model1.fit(noised_scaled_data_C, noised_scaled_data_F, epochs=20)

model1.save('noised_after_learning.h5')

print(model1.predict(np.array([0.01])))

filename = "noised_after_learning.h5"

with h5py.File(filename, 'r') as f:
    # 파일 내용 확인 (예: 키 목록을 출력하거나, 특정 데이터에 접근)
    print(list(f.keys()))
    print(list(f['model_weights']['dense_1']['sequential_1']['dense_1']['kernel']))
    print(list(f['model_weights']['dense_1']['sequential_1']['dense_1']['bias']))

plt.plot(fit_hist.history['loss'])
plt.show()

