# -*- coding: utf-8 -*-
"""AI_exam04_heart_disease_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_7LGSyXM7HL_dP4LWaG4iEDoyAwWG5f
"""

import numpy as np
import pandas as pd # 다양한 확장자 파일 읽어서 변환해주는 패키지
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Dropout

# colunm name 추가 코드
column_names = ['age','gender','cp','treshbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal','HeartDisease']
raw_data = pd.read_excel('./heart-disease.xlsx', names=column_names, index_col=None) # .read_excel : 엑셀파일 읽어줌
print(raw_data.head()) # .head() : 데이터들 중 처음 다섯개 출력(맨좌측 인덱스로 확인가능) <-> .tail()

raw_data.info() # .info() : 데이터 정보 확인

raw_data.describe() # .describ() : column 별 데이터(계산 가능한 형태만) 통계정보 표시
# 결과 해석 : 저장된 값중 숫자가 아닌것이 있으면 pandas에서 object로 변경시켜 사용못하는 column이 됨

# object 타입 column의 '?' 데이터를 숫자형태로 변경
clean_data = raw_data.replace('?', np.nan) # np.nan : 숫자 아닌 데이터타입을 float 형태로 변경(결측치). 계산가능한 값이지만 계산결과는 무조건 nan값(무한대 개념과 비슷)
clean_data.info()
# 결과 해석 : 결측치(nan) 발생으로 인해 데이터 소실 발생(302 non-null에서 개수 감소)

# 결측치 전처리 : 데이터 버리는 방법 cf) 평균값, 최솟값, 최댓값 등으로 채워넣는 방법도 있음
clean_data = clean_data.dropna()
clean_data.info()
# 결과 해석 : 데이터를 버려 295개로 감소

keep = column_names.pop()
print(keep)
print(column_names)

training_data = clean_data[column_names]
target_data = clean_data[[keep]]
print(training_data.head())
print(target_data.head())

# 학습할 데이터가 한 쪽으로 치우치지 않았는지 확인 -> 모델의 편향된 학습을 방지
print(target_data.sum())

# .mean() : 심장병 환자 비율 확인
print(target_data.mean())

# scaling 과정
from sklearn.preprocessing import StandardScaler # StandardScaler : 표준정규분포를 따르는 값들로 스케일링
acaler = StandardScaler()
scaled_data = acaler.fit_transform(training_data)
scaled_data = pd.DataFrame(scaled_data, columns=training_data.columns)
scaled_data.head()

# 평균 0, 표준편차 1로 column 값들이 스케일링 되었는지 확인
scaled_data.describe().T # .T : column과 row switch

# 학습데이터를 일부 분리해 나머지만 학습시키고 다시 분리한 일부로 테스트 하는 과정 : 모델의 판단 편향성을 확인하는 과정
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(scaled_data, target_data, test_size=0.2) # test_size=0.2 : 검증용 데이터 20% 분리
# X - 심장병 판단용 데이터(age, gender, ...), Y - 심장병 판단 결과데이터(0,1)
# _train - 학습용 데이터, _test : 검증용 데이터(20%)
# X와 Y 개수가 쌍을 이루어야 한다 -> train(236개), test(59개)
print(X_train.shape) # .shape : 총 데이터를 (행 개수, 열 개수)로 표현
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

# 학습 모델 선언 : 4-layer 이진분류기
model = Sequential()
model.add(Dense(256, input_dim=13, activation='relu'))
model.add(Dropout(0.3))  # dropout : 랜덤하게 뉴런 중 몇 %는 비활성화한다는 의미 -> 모델 과적합 방지
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid'))  # 이진 분류기의 경우 맨 마지막 perceptron은 1개.
model.summary()

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['binary_accuracy']) # .compile : forward와 backward 과정을 통해 학습하는 과정
fit_hist = model.fit(X_train, Y_train, batch_size=32, epochs=10, validation_split=0.2, verbose=1) # verbose : 출력형태 의미
#validation_split=0.2 :  훈련데이터의 20퍼를 또 분리하여 검증용으로 사용 -> 하이퍼파라미터 튜닝 / Early Stopping / Overfitting 감지

# 테스트 데이터로 모델 성능 확인 결과
score = model.evaluate(X_test, Y_test, verbose=1) #.evaluate : forward 과정만 진행해 모델이 데이터를 학습하지 않고 결과 (loss, accuracy)만 출력. '.compile' 과 차이.
print('loss', score[0])
print('accuracy', score[1]) # F1-Score 지표

# 모델의 학습 데이터에 대한 과적합을 그래프로 판단
plt.plot(fit_hist.history['binary_accuracy'])
plt.plot(fit_hist.history['val_binary_accuracy'])
plt.show()

# confusion matrix
from sklearn.metrics import confusion_matrix, f1_score, recall_score, precision_score
pred = model.predict(X_test) # .predict() : 검증 데이터를 모델에 넣어 학습 -> 결과물 : 값이 1일 확률
pred = pred > 0.1 # sigmoid 판단 기준 0.5 : 0.5보다 크면 1, 아니면 0 -> type1,2 error 중 중요도에 따라 조절.
print(confusion_matrix(Y_test,pred)) # confusion matrix 만들기 : 정답(Y_test)과 모델 예측치(pred)가 얼마나 다른지를 보여주는 지표
print(f1_score(Y_test,pred)) # type 1,2 모두 중요한 경우 높아야함
print(recall_score(Y_test,pred)) # sensitivity. type2 에러가 낮아야하는 경우 높아야 함
print(precision_score(Y_test,pred)) # type1 에러가 낮아야하는 경우 높아야 함

