# -*- coding: utf-8 -*-
"""AI_exam07_classification_mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KtdnfoT6Y8WD_PjhnIylk_bOq6-yM3KB
"""

import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import to_categorical

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

my_sample = np.random.randint(0, X_train.shape[0]) # 6만장 데이터 중 랜덤 1개 뽑기
print(my_sample)
print(Y_train[my_sample]) # 해당 데이터(손글씨)가 뜻하는 숫자.
plt.imshow(X_train[my_sample], cmap='gray') # .imshow() : 이미지 보여주는 함수
plt.show()
print(X_train[my_sample]) # 픽셀 흑백 값을(0 ~ 255) 28 x 28 행렬 크기로 가지는 데이터.

y_train = to_categorical(Y_train) # 0 ~ 9 숫자를 onehotencoding 하여 10비트의 데이터로 표현
y_test = to_categorical(Y_test)
print(y_train.shape)
print(y_test.shape)
print(y_train[my_sample])

x_train = X_train.reshape(60000, 784) # .reshape : 모델은 입력 784(28 * 28 pixel)을 하나의 입력으로 받으므로 인덱싱을 한 겹 제거한다.
x_test = X_test.reshape(10000, 784)
print(x_train[5000])
print(X_train[5000])

x_train = x_train / 255
x_test = x_test / 255
print(X_train.shape)
print(x_train[5000])

model = Sequential()
model.add(Dense(128, input_shape=(784,), activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.summary()

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

fit_hist = model.fit(x_train, y_train, epochs=15, batch_size = 512, validation_split=0.2)

plt.plot(fit_hist.history['loss'], label='Training Loss')
plt.plot(fit_hist.history['val_loss'], label='Validation Loss')
plt.legend()
plt.show()

plt.plot(fit_hist.history['accuracy'], label='Training Accuracy')
plt.plot(fit_hist.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.show()
# training Accuracy 와 Validation Accuracy 사이의 간극은 과적합의 결과라고 볼 수 있음.

score = model.evaluate(x_test, y_test)
print('Final test set accuracy', score[1])

