# -*- coding: utf-8 -*-
"""AI_exam06_iris_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10fm6oBLkjS6nlmfOENwY_s-BsXnq_EqL
"""

# iris 분류 모델 만들기 - 다중분류기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets import load_iris # 꽃 품종 분류 데이터
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

iris = load_iris()
print(type(iris))
print(iris.keys())

iris.data.shape # 150개 개체의 4가지 정보 가지고 있음

iris.feature_names # 개체들의 4가지 정보(학습데이터)

iris.target

iris.target_names # target 품종 3개

iris_dataframe = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_dataframe.head()

pd.plotting.scatter_matrix(iris_dataframe, c=iris.target, figsize=(8,8), s=20, marker='o', alpha=0.3)
plt.show()

x = iris.data
y = iris.target.reshape(-1,1)
print(x.shape)
print(y.shape)

# target인 품종 정보(0,1,2)를 onehotencoding -> 이진 분류기를 여러개 만드는 방식. 출력 결과가 가장 높은 매치율을 가지는 것을 target으로 본다.
encoder = OneHotEncoder(sparse_output=False) # sparse_output=True, False : 출력 방식 차이
encoded_y = encoder.fit_transform(y)
print(encoded_y)

X_train, X_test, Y_train, Y_test = train_test_split(x, encoded_y, test_size=0.2)
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

model = Sequential()
model.add(Dense(10, input_shape=(4,), activation='relu')) # input_shape=(4,) : 입력이 4개(sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax')) # softmax : 이진 분류기 3개의 출력을 확률로 만들어줌
model.compile(optimizer='adam', loss='categorical_crossentropy',metrics=['accuracy'])
model.summary()

fit_hist = model.fit(X_train, Y_train, epochs=100, batch_size=5, validation_data=(X_test,Y_test))

plt.plot(fit_hist.history['accuracy'])
plt.plot(fit_hist.history['val_accuracy'])

score = model.evaluate(X_test,Y_test)
print(score)

