# -*- coding: utf-8 -*-
"""AI_exam03_keras_xor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I7q5nvKxpnmO512-fJ76u-0l_xgk_i28

https://itwiki.kr/w/인공지능
"""

import numpy as np
from keras.models import Sequential
from keras.layers import Dense
import matplotlib.pyplot as plt

# 논리 게이트 학습 데이터
training_data = np.array([[0,0],[0,1],[1,0],[1,1]])
target_data = np.array([[0],[1],[1],[0]])

# AND 게이트 학습할 모델 선언 : multi-layered perceptron
model = Sequential()
model.add(Dense(32, input_dim=2, activation='relu'))  # 중첩 layer 선언(Dense=32) : 32개의 노드(각각 서로다른 bias를 가짐) 선언. 각각이 입력 2개와 연결(각각 서로 다른 weight)됨 #input_dim=2 : 2개의 입력 # relu 함수 : 0이상이면 기울기 1인 그래프. 초기 dense에서의 데이터 소실 없음. # Dense : 차원개념. 숫자가 높아진다 = 차원확장개념(2차원에서는 xor 판단이 어려우므로 차원확장)
model.add(Dense(1, activation='sigmoid')) # 출력단 : 32개 노드의 출력을 입력으로 받음 # sigmoid 함수 : step function을 미분하기 위해 도입. 논리 판단에 많이 사용 - 기울기 최대가 0.25인 한계때문에 vanishing gradient 문제 발생 -> relu 함수 도입 계기
model.compile(loss='mse', optimizer='adam', metrics=['binary_accuracy']) # binary_accuracy : 정확도를 의미. 1이되는 순간부터 loss값이 감소. -> loss 값이 낮을수록 새로운 데이터가 들어올 때 판별을 잘할 수 있음
model.summary() # 첫 번째 param 96개 : 64개의 weight + 32개의 bias # 두 번째 param 33개 : 32개의 weight + 1개의 bias

# 500회 학습
fit_hist = model.fit(training_data, target_data, epochs=500, verbose=1)

# 결과 확인
print(model.predict(np.array([[1,1]])).round())

plt.plot(fit_hist.history['loss'])
plt.show()