# -*- coding: utf-8 -*-
"""AI_exam02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hqw_2XOcHsPjbstCZOX9fPMO-rIPuhpp
"""

import numpy as np

# 경사하강 알고리즘 : mse 값에서의 미분값(양수 또는 음수 또는 0)을 빼주면서 정답 t에 가까워지는 알고리즘. 단, 발산을 막기 위해 그냥 빼지 않고 learing rate(매우 작은값)을 곱해서 조금씩 빼준다.
class mse_graph:
  def __init__(self):
    self.loss = None
    self.x = None
    self.y = None
    self.t = None
  def forward(self,y,t): # x - 학습데이터, y - 모델이 예측한 값, t - 정답
    self.t = t
    self.y = y
    self.loss = np.mean((self.y - self.t)**2) # np.mean : numpy 평균함수
    return self.loss
  def backward(self,x,dout=1):
    data_size = self.t.shape[0] # shape[] : 데이터 사이즈. shape는 (데이터크기,)의 튜플 형태 -> 튜플 요소가 하나일때 콤마가 필요
    dweight_mse = ((self.y - self.t) * x).sum() * 2 / data_size # mse를 weight에 대해 미분
    dbias_mse = (self.y - self.t).sum() * 2 / data_size # mse를 bias에 대해 미분
    return dweight_mse, dbias_mse

# 계산 그래프
class add_graph:
  def __init__(self):
    pass
  def forward(self,x,y):
    out = x+y
    return out
  def backward(self,dout): # 덧셈 미분
    dx = dout * 1
    dy = dout * 1
    return dx, dy

class mul_graph:
  def __init__(self):
    self.x = None
    self.y = None
  def forward(self,x,y):
    self.x = x
    self.y = y
    out = x*y
    return out
  def backward(self,dout): # 곱셈 미분
    dx = dout * self.y
    dy = dout * self.x
    return dx, dy

apple = 100
apple_num = 2
orange = 150
orange_num = 3
tax = 1.1

mul_apple_graph = mul_graph()
mul_orange_graph = mul_graph()
add_apple_orange_graph = add_graph()
mul_tax_graph = mul_graph()

# 양자화 오류
apple_price = mul_apple_graph.forward(apple,apple_num)
orange_price = mul_orange_graph.forward(orange,orange_num)
all_price = add_apple_orange_graph.forward(apple_price,orange_price)
total_price = mul_tax_graph.forward(all_price,tax)
print(total_price)

# 입력이 출력에 미치는 영향 정도를 보여주는 코드
# 미분 개념
dprice = 1
dall_price, dtax = mul_tax_graph.backward(dprice)
dapple_price, dorange_price = add_apple_orange_graph.backward(dall_price)
dorange, dorange_num = mul_orange_graph.backward(dorange_price)
dapple, dapple_num = mul_apple_graph.backward(dapple_price)
print(dapple,dapple_num,dorange,dorange_num, dtax) # 처음부터 각각 사과가격, 사과개수, 오렌지가격, 오렌지개수, 세금액이 1만큼 변할 때 출력(total_price)에 미치는 영향(weight) 수치를 보여준다.

def celsius_to_fahrenheit(x):
  return x*1.8+32

# 모델 생성 : 파라미터(weight, bias)를 초기 선언하고 학습을 통해 조정.
weight = np.random.uniform(0,5,1) #.uniform : random 확률이 모두 비슷하게 설정.
print(weight)
bias = 0

# 100개의 학습 데이터쌍(C, F) 선언
data_C = np.arange(0,100)
data_F = celsius_to_fahrenheit(data_C)
# scaled_data_C = (data_C - data_C.min()) / (data_C.max() - data_C.min()) # min - max scaling : 데이터 값이 너무 크면 mse 발산 가능성이 있으므로 down scaling
# scaled_data_F = (data_F - data_F.min()) / (data_F.max() - data_F.min())
scaled_data_C = data_C / 100 # 위의 표현과 같은 표현
scaled_data_F = data_F / 100
print(scaled_data_C)
print(scaled_data_C.shape)
print(scaled_data_F)
print(scaled_data_F.shape)

# weight, bias 미분 선언
weight_graph = mul_graph()
bias_graph = add_graph()

# 데이터 * weight + bias 하여 시스템 출력 예측
weighted_data_C = weight_graph.forward(scaled_data_C, weight)
predict_data = bias_graph.forward(weighted_data_C, bias)
print(predict_data)

# weight, bias 미분값 확인
dout = 1
dbias, dweighted_data = bias_graph.backward(dout)
print(dbias)
dscaled_data, dweight = weight_graph.backward(dweighted_data)
print(dweight)

# mse 클래스 선언
mseGraph = mse_graph()
mse = mseGraph.forward(predict_data, scaled_data_F) # 예측 데이터와 정답 데이터 간 에러계산
print(mse)

# mse 미분값 확인
weighted_mse_gradient, bias_mse_gradient = mseGraph.backward(scaled_data_C)
print(weighted_mse_gradient)
print(bias_mse_gradient)

learning_rate = 0.1 # 러닝 레이트 크기가 너무 크면 발산 가능성이 있음. 너무 작아도 정확한 추측이 불가능.

# 학습 1회 결과물 확인 : weight와 bias가 서로 영향을 받아 바로 정답을 찾기 어려움 -> 학습 횟수가 많아지면 둘 다 정답에 근접하게 이동.
learned_weight = weight - learning_rate * weighted_mse_gradient * np.average(dweight)
learned_bias = bias - learning_rate * bias_mse_gradient * dbias
print(weight, learned_weight)
print(bias, learned_bias)

# 1000회 학습 코드
error_list = []
weight_list = []
bias_list = []
for i in range(1000):
  #forward
  weighted_data_C = weight_graph.forward(weight, scaled_data_C)
  predict_data = bias_graph.forward(weighted_data_C, bias)
  #backward
  dout = 1
  dbias, dweighted_data = bias_graph.backward(dout)
  dweight, dscaled_data = weight_graph.backward(dweighted_data)
  #mse
  mse = mseGraph.forward(predict_data, scaled_data_F)
  error_list.append(mse)
  #mse gradient
  weighted_mse_gradient, bias_mse_gradient = mseGraph.backward(scaled_data_C)
  #learning
  weight = weight - learning_rate * weighted_mse_gradient * np.average(dweight)
  bias = bias - learning_rate * bias_mse_gradient * dbias
  weight_list.append(weight)
  bias_list.append(bias)
print(weight, bias)

# mse 변화 그래프
import matplotlib.pyplot as plt

plt.plot(error_list)

# weight 추측값 변화 그래프
plt.plot(weight_list)

# bias 추측값 변화 그래프
plt.plot(bias_list)

