# -*- coding: utf-8 -*-
"""AI_exam08_classification_fashion_mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19wFdZ4JlOBDdGiXMZui7P36ue81u4H8d
"""

import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import fashion_mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPooling2D, Flatten
from keras.utils import to_categorical

(X_train, Y_train), (X_test, Y_test) = fashion_mnist.load_data()
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

my_sample = np.random.randint(0, X_train.shape[0]) # 6만장 데이터 중 랜덤 1개 뽑기
print(my_sample)
print(Y_train[my_sample]) # 해당 데이터(손글씨)가 뜻하는 숫자.
plt.imshow(X_train[my_sample], cmap='gray') # .imshow() : 이미지 보여주는 함수
plt.show()
print(X_train[my_sample]) # 픽셀 흑백 값을(0 ~ 255) 28 x 28 행렬 크기로 가지는 데이터.

label = ['T-shirt', 'trouser', 'pullover', 'dress', 'coat', 'sandal', 'shirt', 'sneaker', 'bag', 'ankle_boot']

y_train = to_categorical(Y_train) # 0 ~ 9 숫자를 onehotencoding 하여 10비트의 데이터로 표현
y_test = to_categorical(Y_test)
print(y_train.shape)
print(y_test.shape)
print(y_train[my_sample])

x_train = X_train.reshape(60000, 28, 28, 1) # .reshape(60000, 784) : 모델은 입력 784(28 * 28 pixel)을 하나의 입력으로 받으므로 인덱싱을 한 겹 제거한다. # reshape(60000, 28, 28, 1) : convolution layer에 맞게 input 형태 변경
x_test = X_test.reshape(10000, 28, 28, 1)
print(x_train[5000])
print(X_train[5000])

x_train = x_train / 255
x_test = x_test / 255
print(X_train.shape)
print(x_train[5000])

model = Sequential()
model.add(Conv2D(32, input_shape = (28, 28, 1), activation='relu', kernel_size = (3,3), padding='same')) # padding='same' : input의 모든 pixel을 컨볼루션 하기 위해 원래 input의 크기를 늘려서 컨볼루션(새롭게 생긴 pixel은 0값으로 채움)
# 1st layer param 개수 : (weight 9 + bias 1개(kerenl cell 9개 바이어스를 하나의 상수 취급)) * conv2D_kerenl 32(32개 필터)
model.add(MaxPooling2D(pool_size=(2,2), padding='same')) # MaxPooling : pool_size에서 가장 큰값만 취하는 형태 -> 노이즈 제거에 효과, mul와 add 과정이 없으므로 param(weight, bias)가 존재 x
model.add(Conv2D(32, activation='relu', kernel_size = (3,3), padding='same')) # param 개수 : (3*3*32+1)*32 = 9248 -> (필터 하나는 9 pixel * 32개 입력 + 필터 하나당 bias 1개) * 32개 필터
model.add(MaxPooling2D(pool_size=(2,2), padding='same'))
model.add(Flatten()) # conv 결과를 dense layer의 입력으로 만들기 위해 데이터 형태를 바꾸는 과정 -> 7*7 =-49 pixel * 32개 필터된 데이터 = 1568
model.add(Dense(128, activation='relu')) # 128 * 1568 + 128 = 200,832
model.add(Dense(10, activation='softmax')) # 128 * 10 + 10 = 1290
model.summary()

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

fit_hist = model.fit(x_train, y_train, epochs=15, batch_size = 512, validation_split=0.2)

plt.plot(fit_hist.history['loss'], label='Training Loss')
plt.plot(fit_hist.history['val_loss'], label='Validation Loss')
plt.legend()
plt.show()

plt.plot(fit_hist.history['accuracy'], label='Training Accuracy')
plt.plot(fit_hist.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.show()
# training Accuracy 와 Validation Accuracy 사이의 간극은 과적합의 결과라고 볼 수 있음.

score = model.evaluate(x_test, y_test)
print('Final test set accuracy', score[1])

my_sample = np.random.randint(0, X_test.shape[0])
print('actual', Y_test[my_sample], label[Y_test[my_sample]])
pred = model.predict(x_test[my_sample].reshape(1, 28, 28, 1))
print(pred) # 각 target 들에 해당할 확률 보여줌(activation='softmax') -> 이 중 가장 높은 확률을 가진 것을 target 이라고 예측.
print('predict', np.argmax(pred), label[np.argmax(pred)])
plt.imshow(X_test[my_sample], cmap='gray')
plt.show()

