# -*- coding: utf-8 -*-
"""AI_exam05_titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EdIihV-T0tPRvspkkkie6ewsGvR-D_i8
"""

import seaborn as sns # 도표 그리기용. matplot 보다 조금 더 시각적으로 보기좋음.
import pandas as pd
import numpy as np

raw_data = sns.load_dataset('titanic') # titanic 데이터가 기본적으로 seaborn에 내장되어있음.
print(raw_data.head())

# EDA : Explore data analysis. 탐색적 자료분석과정 꼭 필요.
raw_data.info()

raw_data.isnull().sum() # .isnull() : null 개수 판단

# NaN 값이 많은 'deck' column 데이터 버리기
clean_data = raw_data.dropna(axis=1, thresh=500) # .dropna(axis=1, thresh=500) : nan 값이 500개 이상인 column은 버린다. row를 버리려면 axix=0 설정
print(clean_data.columns)

# 일부 NaN 이 존재하는 'age' 항목을 평균으로 채워넣기
clean_data['age'].fillna(clean_data['age'].mean(), inplace=True) # .fillna(inplace=True) : NaN 값을 채우고 원본을 수정한다는 뜻(inplace=True). inpplace=False이면 수정 사본(파일 요구)을 만든다.
print(clean_data.isnull().sum())

# 나이를 전체 승객 평균으로 채웠음. 승객 특성에 따라 나이 평균을 다르게 계산해서 넣는 것도 생각해보기.
clean_data.age[:20]

# 중복 데이터를 가지는 column 버리기(데이터 가공을 해야 되는 column을 버린다.)
clean_data.drop(['embark_town','alive','class'], axis=1, inplace=True)
print(clean_data.columns)

# 'embarked' column의 NaN 데이터 채우기
clean_data['embarked'].fillna(method='ffill',inplace=True) # method='ffill' : 이전 row 값으로 채우는 방법 <-> bfill
print(clean_data.isnull().sum())

clean_data.info()

clean_data['sex'].replace({'male':0, 'female':1}, inplace=True) # 딕셔너리 형태로 여러개 replace 하기
print(clean_data['sex'].unique()) # .unique() : 대상에 어떤 값들이 들어있는지 확인

print(clean_data.embarked.value_counts()) # 데이터프레임의 컬럼명으로 접근도 가능 = 인덱싱 방법과 동일
# .value_counts : 어떤 항목이 몇 개 있는지 count

# LabelEncoder : 문자열 정보를 encoding(숫자로 변환)
from re import L
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
clean_data['embarked'] = encoder.fit_transform(clean_data['embarked'])
print(clean_data['embarked'].value_counts())

print(clean_data.who.value_counts())

clean_data['who'] = encoder.fit_transform(clean_data['who'])
print(clean_data['who'].value_counts())

clean_data.info()

# .astype('') : bool 타입을 int64로 바꿈(단, 변환할 데이터들이 변환 가능한 형태인 경우에만 가능)
clean_data['adult_male'] = clean_data['adult_male'].astype('int64')
clean_data['alone'] = clean_data['alone'].astype('int64')
clean_data.info()

# target 추출

target = clean_data['survived']
print(type(clean_data))
print(type(target)) # pandas data type : series(column이 1개짜리 데이터)와 dataframe(표 형태)
print(target)
target = clean_data[['survived']] # 리스트를 두 번 에워싸면 dataframe 형식이 됨.
print(type(target))

# .columns : column 이름명(변수)
clean_data.columns

# 학습데이터에서 target 분리
training_data = clean_data.drop(['survived'],axis=1)
training_data

# 다운스케일링 필요한 데이터만 추출
value_data = training_data[['age','fare']]
print(value_data.head())

# Standard scaling : 진행 후 dataframe으로 다시 형변환 필요
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(value_data)
print(type(scaled_data)) # 데이터 타입이 변경됨 -> dataframe으로 다시 형변환 필요
value_data = pd.DataFrame(scaled_data, columns=value_data.columns)
print(value_data.head())
print(type(value_data))

# 계산 불가능한 척도들 처리하기

training_data.drop(['age','fare'],axis=1,inplace=True) # 계산가능한 척도들은 분리
training_data

# 가변수화(dummy화) -> onehot code 형태 : column 중에 무조건 한 개만 1인 형태
onehot_data = pd.get_dummies(training_data, columns=training_data.columns)
onehot_data

# onehot_data 형변환
onehot_data = onehot_data.astype('int')
onehot_data.info()

# pd.concat : 가공한 데이터(value_data, onehot_data) 취합
training_data = pd.concat([onehot_data, value_data],axis=1)
training_data

# 테스트용 데이터(20%)와 학습용 데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(training_data, target, test_size=0.2)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

target.mean()

# .loc : 특정 데이터 뽑아내는 함수
man = raw_data.loc[raw_data.sex == 'male'] # male 값을 가진 데이터만 뽑기
print(man.survived.mean())
woman = raw_data.loc[raw_data.sex == 'female'] # female 값을 가진 데이터만 뽑기
print(woman.survived.mean())
child = raw_data.loc[raw_data.age < 18] # age가 18보다 작은 데이터만 뽑기
print(child.survived.mean())

# 생존한 사람들의 데이터 평균 확인
sur = clean_data.loc[clean_data.survived == 1]
sur.mean()

# 전체 데이터 평균 확인
clean_data.mean()

from keras.models import Sequential
from keras.layers import Dense, Dropout

model = Sequential()
model.add(Dense(128, input_dim=X_train.shape[1], activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

fit_hist = model.fit(X_train, Y_train, epochs=30, batch_size=64, validation_split=0.2) # validation_data=(,) : 학습 중간 검증용 데이터를 사용자가 직접 넣을수 있음.

import matplotlib.pyplot as plt
plt.plot(fit_hist.history['accuracy'])
plt.plot(fit_hist.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train','Validation'], loc='upper left') # 범례
plt.show()

score = model.evaluate(X_test, Y_test)
print('Test loss:',score[0])
print('Test accuracy:',score[1])

