# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jaehyeok95/team_project_npu/team_project_npu.srcs/sources_1/bd/soc_npu/ip/soc_npu_axi_dma_0_1/soc_npu_axi_dma_0_1.xci
# IP: The module: 'soc_npu_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jaehyeok95/team_project_npu/team_project_npu.gen/sources_1/bd/soc_npu/ip/soc_npu_axi_dma_0_1/soc_npu_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_npu_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jaehyeok95/team_project_npu/team_project_npu.gen/sources_1/bd/soc_npu/ip/soc_npu_axi_dma_0_1/soc_npu_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_npu_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jaehyeok95/team_project_npu/team_project_npu.gen/sources_1/bd/soc_npu/ip/soc_npu_axi_dma_0_1/soc_npu_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_npu_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/jaehyeok95/team_project_npu/team_project_npu.srcs/sources_1/bd/soc_npu/ip/soc_npu_axi_dma_0_1/soc_npu_axi_dma_0_1.xci
# IP: The module: 'soc_npu_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jaehyeok95/team_project_npu/team_project_npu.gen/sources_1/bd/soc_npu/ip/soc_npu_axi_dma_0_1/soc_npu_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_npu_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jaehyeok95/team_project_npu/team_project_npu.gen/sources_1/bd/soc_npu/ip/soc_npu_axi_dma_0_1/soc_npu_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_npu_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jaehyeok95/team_project_npu/team_project_npu.gen/sources_1/bd/soc_npu/ip/soc_npu_axi_dma_0_1/soc_npu_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_npu_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
