domain_path: /media/user14/data/work/soc_2026_workspace/platform_watchRev8/export/platform_watchRev8/sw/standalone_microblaze_riscv_0
app_src_dir: /media/user14/data/tools/xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
