# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user14/project_CAN/project_CAN.srcs/sources_1/bd/soc_rtos_ver1/ip/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0.xci
# IP: The module: 'soc_rtos_ver1_microblaze_riscv_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user14/project_CAN/project_CAN.gen/sources_1/bd/soc_rtos_ver1/ip/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0_1/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_rtos_ver1_microblaze_riscv_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user14/project_CAN/project_CAN.gen/sources_1/bd/soc_rtos_ver1/ip/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0_1/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_rtos_ver1_microblaze_riscv_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user14/project_CAN/project_CAN.gen/sources_1/bd/soc_rtos_ver1/ip/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0_1/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_rtos_ver1_microblaze_riscv_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/user14/project_CAN/project_CAN.srcs/sources_1/bd/soc_rtos_ver1/ip/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0.xci
# IP: The module: 'soc_rtos_ver1_microblaze_riscv_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user14/project_CAN/project_CAN.gen/sources_1/bd/soc_rtos_ver1/ip/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0_1/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_rtos_ver1_microblaze_riscv_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user14/project_CAN/project_CAN.gen/sources_1/bd/soc_rtos_ver1/ip/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0_1/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_rtos_ver1_microblaze_riscv_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user14/project_CAN/project_CAN.gen/sources_1/bd/soc_rtos_ver1/ip/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0_1/soc_rtos_ver1_microblaze_riscv_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_rtos_ver1_microblaze_riscv_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
