# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/soc_npu/soc_npu.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_npu || ORIG_REF_NAME==soc_npu} -quiet] -quiet

# IP: bd/soc_npu/ip/soc_npu_processing_system7_0_1/soc_npu_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_npu_processing_system7_0_1 || ORIG_REF_NAME==soc_npu_processing_system7_0_1} -quiet] -quiet

# IP: bd/soc_npu/ip/soc_npu_myip_npu_OCR_0_1/soc_npu_myip_npu_OCR_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_npu_myip_npu_OCR_0_1 || ORIG_REF_NAME==soc_npu_myip_npu_OCR_0_1} -quiet] -quiet

# IP: bd/soc_npu/ip/soc_npu_axi_dma_0_1/soc_npu_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_npu_axi_dma_0_1 || ORIG_REF_NAME==soc_npu_axi_dma_0_1} -quiet] -quiet

# IP: bd/soc_npu/ip/soc_npu_axi_smc_1/soc_npu_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_npu_axi_smc_1 || ORIG_REF_NAME==soc_npu_axi_smc_1} -quiet] -quiet

# IP: bd/soc_npu/ip/soc_npu_rst_ps7_0_50M_1/soc_npu_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_npu_rst_ps7_0_50M_1 || ORIG_REF_NAME==soc_npu_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/soc_npu/ip/soc_npu_axi_mem_intercon_imp_xbar_0/soc_npu_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_npu_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==soc_npu_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/soc_npu/ip/soc_npu_axi_mem_intercon_0/soc_npu_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_npu_axi_mem_intercon_0 || ORIG_REF_NAME==soc_npu_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/soc_npu/ip/soc_npu_axi_mem_intercon_imp_auto_us_0/soc_npu_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_npu_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==soc_npu_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/soc_npu/ip/soc_npu_axi_mem_intercon_imp_auto_pc_0/soc_npu_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_npu_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==soc_npu_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# XDC: /home/jaehyeok95/team_project_npu/team_project_npu.gen/sources_1/bd/soc_npu/soc_npu_ooc.xdc
