# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Basys-3-Master.xdc

# Block Designs: bd/soc_rtos_can/soc_rtos_can.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can || ORIG_REF_NAME==soc_rtos_can} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_proc_sys_reset_0_0/soc_rtos_can_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_proc_sys_reset_0_0 || ORIG_REF_NAME==soc_rtos_can_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_clk_wiz_0/soc_rtos_can_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_clk_wiz_0 || ORIG_REF_NAME==soc_rtos_can_clk_wiz_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_microblaze_riscv_0_0/soc_rtos_can_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_microblaze_riscv_0_0 || ORIG_REF_NAME==soc_rtos_can_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_dlmb_v10_0/soc_rtos_can_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_dlmb_v10_0 || ORIG_REF_NAME==soc_rtos_can_dlmb_v10_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_ilmb_v10_0/soc_rtos_can_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_ilmb_v10_0 || ORIG_REF_NAME==soc_rtos_can_ilmb_v10_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_dlmb_bram_if_cntlr_0/soc_rtos_can_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==soc_rtos_can_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_ilmb_bram_if_cntlr_0/soc_rtos_can_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==soc_rtos_can_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_lmb_bram_0/soc_rtos_can_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_lmb_bram_0 || ORIG_REF_NAME==soc_rtos_can_lmb_bram_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_microblaze_riscv_0_axi_periph_imp_xbar_0/soc_rtos_can_microblaze_riscv_0_axi_periph_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_microblaze_riscv_0_axi_periph_imp_xbar_0 || ORIG_REF_NAME==soc_rtos_can_microblaze_riscv_0_axi_periph_imp_xbar_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_microblaze_riscv_0_axi_periph_0/soc_rtos_can_microblaze_riscv_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_microblaze_riscv_0_axi_periph_0 || ORIG_REF_NAME==soc_rtos_can_microblaze_riscv_0_axi_periph_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_microblaze_riscv_0_axi_intc_0/soc_rtos_can_microblaze_riscv_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_microblaze_riscv_0_axi_intc_0 || ORIG_REF_NAME==soc_rtos_can_microblaze_riscv_0_axi_intc_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_microblaze_riscv_0_xlconcat_0/soc_rtos_can_microblaze_riscv_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_microblaze_riscv_0_xlconcat_0 || ORIG_REF_NAME==soc_rtos_can_microblaze_riscv_0_xlconcat_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_mdm_1_0/soc_rtos_can_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_mdm_1_0 || ORIG_REF_NAME==soc_rtos_can_mdm_1_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_axi_uartlite_0_0/soc_rtos_can_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_axi_uartlite_0_0 || ORIG_REF_NAME==soc_rtos_can_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_myip_can_0_0/soc_rtos_can_myip_can_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_myip_can_0_0 || ORIG_REF_NAME==soc_rtos_can_myip_can_0_0} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_axi_timer_0_1/soc_rtos_can_axi_timer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_axi_timer_0_1 || ORIG_REF_NAME==soc_rtos_can_axi_timer_0_1} -quiet] -quiet

# IP: bd/soc_rtos_can/ip/soc_rtos_can_myip_RTOS_0_1/soc_rtos_can_myip_RTOS_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_rtos_can_myip_RTOS_0_1 || ORIG_REF_NAME==soc_rtos_can_myip_RTOS_0_1} -quiet] -quiet

# XDC: /home/user14/project_CAN/project_CAN.gen/sources_1/bd/soc_rtos_can/soc_rtos_can_ooc.xdc
