# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/user14/data/work/SOC_exam_2026/SOC_exam_2026.srcs/sources_1/bd/soc_watchRev2/ip/soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0/soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0.xci
# IP: The module: 'soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/user14/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_watchRev2/ip/soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0/soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /media/user14/data/work/SOC_exam_2026/SOC_exam_2026.srcs/sources_1/bd/soc_watchRev2/ip/soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0/soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0.xci
# IP: The module: 'soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/user14/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_watchRev2/ip/soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0/soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
