# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Basys-3-Master.xdc

# Block Designs: bd/soc_watchRev2/soc_watchRev2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2 || ORIG_REF_NAME==soc_watchRev2} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_proc_sys_reset_0_0/soc_watchRev2_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_proc_sys_reset_0_0 || ORIG_REF_NAME==soc_watchRev2_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_clk_wiz_0/soc_watchRev2_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_clk_wiz_0 || ORIG_REF_NAME==soc_watchRev2_clk_wiz_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_microblaze_riscv_0_0/soc_watchRev2_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_microblaze_riscv_0_0 || ORIG_REF_NAME==soc_watchRev2_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_dlmb_v10_0/soc_watchRev2_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_dlmb_v10_0 || ORIG_REF_NAME==soc_watchRev2_dlmb_v10_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_ilmb_v10_0/soc_watchRev2_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_ilmb_v10_0 || ORIG_REF_NAME==soc_watchRev2_ilmb_v10_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_dlmb_bram_if_cntlr_0/soc_watchRev2_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==soc_watchRev2_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_ilmb_bram_if_cntlr_0/soc_watchRev2_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==soc_watchRev2_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_lmb_bram_0/soc_watchRev2_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_lmb_bram_0 || ORIG_REF_NAME==soc_watchRev2_lmb_bram_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0/soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0 || ORIG_REF_NAME==soc_watchRev2_microblaze_riscv_0_axi_periph_imp_xbar_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_microblaze_riscv_0_axi_periph_0/soc_watchRev2_microblaze_riscv_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_microblaze_riscv_0_axi_periph_0 || ORIG_REF_NAME==soc_watchRev2_microblaze_riscv_0_axi_periph_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_microblaze_riscv_0_axi_intc_0/soc_watchRev2_microblaze_riscv_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_microblaze_riscv_0_axi_intc_0 || ORIG_REF_NAME==soc_watchRev2_microblaze_riscv_0_axi_intc_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_microblaze_riscv_0_xlconcat_0/soc_watchRev2_microblaze_riscv_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_microblaze_riscv_0_xlconcat_0 || ORIG_REF_NAME==soc_watchRev2_microblaze_riscv_0_xlconcat_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_mdm_1_0/soc_watchRev2_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_mdm_1_0 || ORIG_REF_NAME==soc_watchRev2_mdm_1_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_axi_uartlite_0_0/soc_watchRev2_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_axi_uartlite_0_0 || ORIG_REF_NAME==soc_watchRev2_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_axi_gpio_0_1/soc_watchRev2_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_axi_gpio_0_1 || ORIG_REF_NAME==soc_watchRev2_axi_gpio_0_1} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_myip_koreawatch_0_0/soc_watchRev2_myip_koreawatch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_myip_koreawatch_0_0 || ORIG_REF_NAME==soc_watchRev2_myip_koreawatch_0_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_myip_stopwatch_0_0/soc_watchRev2_myip_stopwatch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_myip_stopwatch_0_0 || ORIG_REF_NAME==soc_watchRev2_myip_stopwatch_0_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_myip_timer_0_0/soc_watchRev2_myip_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_myip_timer_0_0 || ORIG_REF_NAME==soc_watchRev2_myip_timer_0_0} -quiet] -quiet

# IP: bd/soc_watchRev2/ip/soc_watchRev2_myip_iic_cntr_0_0/soc_watchRev2_myip_iic_cntr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_watchRev2_myip_iic_cntr_0_0 || ORIG_REF_NAME==soc_watchRev2_myip_iic_cntr_0_0} -quiet] -quiet

# XDC: /media/user14/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_watchRev2/soc_watchRev2_ooc.xdc
